"""Create the v1 authentication schema.

Forward recovery: after deployment, repair mistakes with a new forward Alembic revision so audit
and identity history remain intact. This tested downgrade exists for isolated validation and
pre-release rollback only; it intentionally drops all authentication data.

Revision ID: 001
Revises:
Create Date: 2026-08-09 17:22:07.236403
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the forward schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("state_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column("nonce_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column("pkce_verifier_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("encryption_key_id", sa.String(length=100), nullable=False),
        sa.Column("return_path", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_digest", name="uq_oauth_transactions_state_digest"),
    )
    op.create_index(
        "ix_oauth_transactions_expires", "oauth_transactions", ["expires_at"], unique=False
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')", name="ck_organizations_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_organizations_slug"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("normalized_email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("auth_generation", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('CANDIDATE', 'MANAGER', 'ADMIN')", name="ck_users_role"),
        sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')", name="ck_users_status"),
        sa.CheckConstraint("auth_generation >= 1", name="ck_users_auth_generation"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], name="fk_users_organization"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "org_id", name="uq_users_id_org"),
        sa.UniqueConstraint("org_id", "normalized_email", name="uq_users_org_normalized_email"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("target_user_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("reason_code", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=True),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("correlation_id", sa.String(length=100), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("outcome IN ('SUCCESS', 'DENIED')", name="ck_audit_events_outcome"),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], name="fk_audit_events_actor"),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name="fk_audit_events_organization"
        ),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], name="fk_audit_events_target"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_events_correlation", "audit_events", ["correlation_id"], unique=False)
    op.create_index(
        "ix_audit_events_org_occurred", "audit_events", ["org_id", "occurred_at"], unique=False
    )
    op.create_table(
        "authentication_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column("csrf_token_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column("auth_generation", sa.BigInteger(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocation_reason", sa.String(length=40), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "revocation_reason IS NULL OR revocation_reason IN "
            "('LOGOUT_ALL', 'ROLE_CHANGED', 'ACCOUNT_DISABLED', 'ABSOLUTE_EXPIRED', "
            "'IDLE_EXPIRED', 'SECURITY_REVOKED')",
            name="ck_authentication_sessions_revocation_reason",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "org_id"],
            ["users.id", "users.org_id"],
            name="fk_authentication_sessions_user_org",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_digest", name="uq_authentication_sessions_token_digest"),
    )
    op.create_index(
        "ix_authentication_sessions_absolute_expires",
        "authentication_sessions",
        ["absolute_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_authentication_sessions_idle_expires",
        "authentication_sessions",
        ["idle_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_authentication_sessions_user_revoked",
        "authentication_sessions",
        ["user_id", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "candidate_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "org_id"],
            ["users.id", "users.org_id"],
            name="fk_candidate_profiles_user_org",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_candidate_profiles_user"),
    )
    op.create_table(
        "external_login_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("issuer", sa.String(length=500), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email_snapshot", sa.String(length=320), nullable=True),
        sa.Column("bound_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_authenticated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("provider = 'GOOGLE'", name="ck_external_identity_provider"),
        sa.ForeignKeyConstraint(
            ["user_id", "org_id"],
            ["users.id", "users.org_id"],
            name="fk_external_identity_user_org",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "issuer", "subject", name="uq_external_identity_subject"),
        sa.UniqueConstraint("user_id", "provider", name="uq_external_identity_user_provider"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change for tested release rollback."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("external_login_identities")
    op.drop_table("candidate_profiles")
    op.drop_index("ix_authentication_sessions_user_revoked", table_name="authentication_sessions")
    op.drop_index("ix_authentication_sessions_idle_expires", table_name="authentication_sessions")
    op.drop_index(
        "ix_authentication_sessions_absolute_expires", table_name="authentication_sessions"
    )
    op.drop_table("authentication_sessions")
    op.drop_index("ix_audit_events_org_occurred", table_name="audit_events")
    op.drop_index("ix_audit_events_correlation", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("users")
    op.drop_table("organizations")
    op.drop_index("ix_oauth_transactions_expires", table_name="oauth_transactions")
    op.drop_table("oauth_transactions")
    # ### end Alembic commands ###
